# Generated by Django 3.0.5 on 2020-04-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_orderupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
